import type { Fn } from './types';
export declare function isFunction<T extends Fn>(val: any): val is T;
export declare const isDef: <T = any>(val?: T | undefined) => val is T;
export declare function isUndef(value: unknown): value is undefined;
export declare const isBoolean: (val: any) => val is boolean;
export declare const isNumber: (val: any) => val is number;
export declare function isString(val: unknown): val is string;
export declare function isObject(val: any): val is object;
export declare const isDev: boolean;
export declare const isBrowser: boolean;
export declare const isNavigator: boolean;
export declare function noop(): void;
export declare const isIOS: boolean | "";
export declare const isReactLegacy = false;
